version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.28
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elk
    ports:
      - "9200:9200" # Expose Elasticsearch port

  logstash:
    image: logstash:7.17.28
    container_name: logstash
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml  # Mount logstash.yml
    networks:
      - elk
    ports:
      - "5000:5000/tcp"  # Явное указание TCP
      - "5044:5044"
      - "9600:9600"      # Expose Health Check API port (optional for external access)

  kibana:
    image: kibana:7.17.28
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601" # Expose Kibana port

networks:
  elk:
    driver: bridge