version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:7.17.26
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elk
    ports:
      - "9200:9200" # Expose Elasticsearch port

  logstash:
    image: logstash:7.17.26
    container_name: logstash
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    networks:
      - elk
    ports:
      - "5000:5000/tcp" # Expose Logstash port for TCP
      - "5044:5044"     # Expose Logstash port for Beats

  kibana:
    image: kibana:7.17.26
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601" # Expose Kibana port

networks:
  elk:
    driver: bridge